name: Generate and deploy documents to Pages

on:
  push:
    branches:
      - master

jobs:
  Docs-Gen-Pages-Deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install weasyprint php cmark
      - name: step 0/3 checkout
        uses: actions/checkout@v4
      - name: step 1/3 configure
        uses: actions/configure-pages@v5
      - run: |
          cd ${{ github.workspace }}
          ( cd docs-src/spec ; sh ../src/hc-cmd.sh -s ; sh ../src/hc-cmd.sh -m ;
            weasyprint build/singlepage/main.html build/cxing-spec-draft.pdf )
          mv docs-src/spec/build docs
      - name: step 2/3 artifact upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
      - name: step 3/3 deploy
        id: deployment
        uses: actions/deploy-pages@v4
